services:
  - type: web
    name: backend-fastapi-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    runtime: python
    pythonVersion: 3.10.11
